name: continous_deploy_

on:
  workflow_run:
    types: [completed]
    workflows: continuous_integration

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Pull Docker Image
      run: |
        docker system prune
        docker pull erikaysalazarv/todoapp:latest
      
    - name: Start Docker Container
      run: |
       docker  run -d -p 3000:3000 erikaysalazarv/todoapp:latest
