name: continous_deploy

on: [push]
 
jobs:
  deploy:
    runs-on: self-hosted
    
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Pull Docker Image
      run: |
        docker pull erikaysalazarv/todoapp:latest

    - name: Deploy Docker Image
      run: |
        sudo docker run -p 8081:3000 -d erikaysalazarv/todoapp:latest
        
    - name: Start Docker Container
      run: |
        docker run -d --name todoapp2 -p 192.168.100.90:1995:3000 erikaysalazarv/todoapp:latest
