name: continous_deploy

on: [push]
 
jobs:
  deploy:
    runs-on: self-hosted
    
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Pull Docker Image
      run: |
        docker pull erikaysalazarv/todoapp:latest
      
    - name: Start Docker Container
      run: |
        docker run -d --name dockerapp1 -p 127.20.95.5:8080:3000 erikaysalazarv/todoapp:latest
