name: continous_deploy_

on: [push]
 
jobs:
  deploy:
    runs-on: self-hosted
    
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Pull Docker Image
      uses: docker/pull-action@v2
      with:
        source: erikaysalazarv/todoapp
        tag: latest

    - name: Deploy Docker Image
      run: |
        sudo docker run -p 8080:3000 -d erikaysalazarv/todoapp:latest

