name: continous_deploy

on:
  workflow_run:
    types: [completed]
    workflows:
      - CI
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get CI Workflow Output
      id: getoutput
      uses: actions/bin/filter@v2
      with:
        args: workflow run query

    - name: B_
      if: steps.getoutput.outputs.job-a-result == 'success'
      run: echo "Ejecutando tarea B"
