name: continuous_integration

on: [push]

jobs:
  test-build-release:
    runs-on: ubuntu-latest
    env:
      working-directory: ./app/
      NODE_VERSION: 14

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install dependencies
      working-directory: ${{ env.working-directory }}
      run: |
        if [ -e yarn.lock ]; then
          echo "Yarn lockfile found, using yarn to install dependencies"
          yarn
        else
          echo "No yarn lockfile found, using npm to install dependencies"
          npm ci
        fi
      
    - name: Test the app
      working-directory: ${{ env.working-directory }} 
      run: npm test
      env:
        NODE_ENV: test

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    -  name: Build and push
       uses: docker/build-push-action@v4
       with:
          context: ./app
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todoapp:latest
